GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type:  application/json

{
    "text": "Buy the eggs"
}

###

DELETE  http://localhost:3001/todo/delete/64817a30b3ce076489d5ff13

###

PUT http://localhost:3001/todo/complete/64817a90b3ce076489d5ff15